<template>
   <div class="privacy-policy">
      <!--  -->
      <section class="pt-3">
         <div class="container">
            <div class="row justify-content-center">
               <div class="col-xl-10 p-0">
                  <h1 class="h1 text-dark-heading mb-3 mt-5">Privacy Policy</h1>
                  <p class="f2 text-dark-content mb-2">If the internet offer provides the opportunity to enter personal or business data (email addresses, name, addresses), the user divulgence of this data by the user is effected expressly on a voluntary basis. The use and payment of all offered services is permitted - if technically possible and reasonable - without providing any personal data or by providing anonymised data or a pseudonym. The use of contact data published in the imprint or comparable data such as postal addresses, telephone or fax numbers and email addresses for sending unsolicited information is prohibited. INTERLINE Chauffeurservice Eschborn GmbH expressly reserves the right to take legal action against senders of spam mails violating this prohibition.</p>
                  <p class="f2 text-dark-content mb-4">This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”).</p>
                  <p class="f2 text-dark-content mb-4">Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States.</p>
                  <p class="f2 text-dark-content mb-4">In case of activation of the IP anonymization, Google will truncate/anonymize the last octet of the IP address for Member States of the European Union as well as for other parties to the Agreement on the European Economic Area.</p>
                  <p class="f2 text-dark-content mb-4">Only in exceptional cases, the full IP address is sent to and shortened by Google servers in the USA.</p>
                  <p class="f2 text-dark-content mb-4">On behalf of the website provider Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage to the website provider.</p>
                  <p class="f2 text-dark-content mb-4">Google will not associate your IP address with any other data held by Google.</p>
                  <p class="f2 text-dark-content mb-4">You may refuse the use of cookies by selecting the appropriate settings on your browser. However, please note that if you do this, you may not be able to use the full functionality of this website.</p>
                  <p class="f2 text-dark-content mb-4">
                     Furthermore you can prevent Google’s collection and use of data (cookies and IP address) by downloading and installing the browser plug-in available under
                     <a href="https://tools.google.com/dlpage/gaoptout?hl=en-GB.">https://tools.google.com/dlpage/gaoptout?hl=en-GB.</a>
                  </p>
                  <p class="f2 text-dark-content mb-4">
                     You can refuse the use of Google Analytics by clicking on the following link. An opt-out cookie will be set on the computer, which prevents the future collection of your data when visiting this website:
                     <a id="disable-ga" onclick="alert('Google Analytics has been disabled');" href="javascript:gaOptout()">Disable Google Analytics</a>
                  </p>
                  <p class="f2 text-dark-content mb-4">
                     Further information concerning the terms and conditions of use and data privacy can be found at
                     <a href="http://www.google.com/analytics/terms/gb.html">http://www.google.com/analytics/terms/gb.html</a>
                     or at
                     <a href="https://www.google.de/intl/en_uk/policies/">https://www.google.de/intl/en_uk/policies/</a>
                  </p>
                  <p class="f2 text-dark-content mb-4">
                     Please note that on this website, Google Analytics code is supplemented by “gat._anonymizeIp();” to ensure an anonymized collection of IP addresses (so called IP-masking).
                  </p>

               </div>
            </div>
         </div>
      </section>
      <!--  -->

      <LocationsAndOffices />
   </div>
</template>

<script>
import LocationsAndOffices from "../components/global/LocationsAndOffices";
export default {
	name: "privacy-policy",
	components: {
		LocationsAndOffices
	},
	data() {
		return {};
	}
};
</script>

<style>
</style>
